# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-11-14 12:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('log_authority', models.CharField(max_length=1)),
                ('new_data_authority', models.CharField(max_length=1)),
                ('origin_data_authority', models.CharField(max_length=1)),
            ],
        ),
    ]
